
version: 1

sources:
  - name: oliststaging
    database: "olist_database"
    schema: "public"
    tables:
      - name: olist_customers_dataset
        description: "Tabela com customer_id, customer_unique_id, customer_zip_code_prefix, customer_city e customer_state."
        columns:
          - name: customer_id
            description: "Identificador único do cliente."
          - name: customer_unique_id
            description: "Identificador único do cliente (pode ser diferente do customer_id)."
          - name: customer_zip_code_prefix
            description: "Prefixo do código postal do cliente."
          - name: customer_city
            description: "Cidade do cliente."
          - name: customer_state
            description: "Estado do cliente."

      - name: olist_geolocation_dataset
        description: "Tabela contendo informações de geolocalização, incluindo geolocation_zip_code_prefix, geolocation_lat e geolocation_lng, geolocation_city e geolocation_state."
        columns:
          - name: geolocation_zip_code_prefix
            description: "Prefixo do código postal da geolocalização."
          - name: geolocation_lat
            description: "Latitude da geolocalização."
          - name: geolocation_lng
            description: "Longitude da geolocalização."
          - name: geolocation_city
            description: "Cidade da geolocalização."
          - name: geolocation_state
            description: "Estado da geolocalização."


      - name: olist_order_items_dataset
        description: "Tabela de localidades com informações sobre order_id, order_item_id, product_id, seller_id, shipping_limit_date, price e freight_value."
        columns:
          - name: order_id
            description: "Identificador único da ordem de compra."
          - name: order_item_id
            description: "Identificador único do item da ordem de compra."
          - name: product_id
            description: "Identificador único do produto."
          - name: seller_id
            description: "Identificador único do vendedor."
          - name: shipping_limit_date
            description: "Data limite para envio do item."
          - name: price
            description: "Preço unitário do item."
          - name: freight_value
            description: "Valor do frete do item."
         

      - name: olist_order_payments_dataset
        description: "Tabela de pagamentos de ordens de compra com colunas de order_id, payment_sequential, payment_type, payment_installments e payment_value."
        columns:
          - name: order_id
            description: "Identificador único da ordem de compra."
          - name: payment_sequential
            description: "Sequência do pagamento dentro da ordem de compra."
          - name: payment_type
            description: "Tipo de pagamento utilizado."
          - name: payment_installments
            description: "Número de parcelas do pagamento."
          - name: payment_value
            description: "Valor total do pagamento."

      - name: olist_order_reviews_dataset
        description: "Tabela de reviews  com colunas de review_id, order_id, review_score, review_comment_title, review_comment_message e review_creation_date."
        columns:
          - name: review_id
            description: "Identificador único da avaliação (review)."
          - name: order_id
            description: "Identificador único da ordem de compra."
          - name: review_score
            description: "Pontuação da avaliação."
          - name: review_comment_title
            description: "Título do comentário da avaliação."
          - name: review_comment_message
            description: "Mensagem do comentário da avaliação."
          - name: review_creation_date
            description: "Data de criação da avaliação."
          - name: review_answer_timestamp
            description: "Timestamp da resposta à avaliação."
      - name: olist_orders_dataset
        description: "Tabela de ordens de compra com colunas de order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date e order_estimated_delivery_date."
        columns:
          - name: order_id
            description: "Identificador único da ordem de compra."
          - name: customer_id
            description: "Identificador único do cliente que realizou a compra."
          - name: order_status
            description: "Status atual da ordem de compra."
          - name: order_purchase_timestamp
            description: "Timestamp da compra da ordem de compra."
          - name: order_approved_at
            description: "Timestamp de aprovação da ordem de compra."
          - name: order_delivered_carrier_date
            description: "Data de entrega ao transportador da ordem de compra."
          - name: order_delivered_customer_date
            description: "Data de entrega ao cliente da ordem de compra."
          - name: order_estimated_delivery_date
            description: "Data estimada para entrega da ordem de compra."
      - name: olist_products_dataset
        description: "Tabela de produtos com colunas de product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm e product_width_cm."
        columns:
          - name: product_id
            description: "Identificador único do produto."
          - name: product_category_name
            description: "Categoria do produto."
          - name: product_name_lenght
            description: "Comprimento do nome do produto."
          - name: product_description_lenght
            description: "Comprimento da descrição do produto."
          - name: product_photos_qty
            description: "Quantidade de fotos do produto."
          - name: product_weight_g
            description: "Peso do produto em gramas."
          - name: product_length_cm
            description: "Comprimento do produto em centímetros."
          - name: product_height_cm
            description: "Altura do produto em centímetros."
          - name: product_width_cm
            description: "Largura do produto em centímetros."
      - name: olist_sellers_dataset
        description: "Tabela de vendedores com colunas de seller_id, seller_zip_code_prefix, seller_city e seller_state."
        columns:
          - name: seller_id
            description: "Identificador único do vendedor."
          - name: seller_zip_code_prefix
            description: "Prefixo do código postal do vendedor."
          - name: seller_city
            description: "Cidade do vendedor."
          - name: seller_state
            description: "Estado do vendedor."
      - name: product_category_name_translation
        description: "Tabela de tradução de categorias de produtos com colunas de product_category_name e product_category_name_english."
        columns:
          - name: product_category_name
            description: "Nome da categoria do produto em português."
          - name: product_category_name_english
            description: "Nome da categoria do produto em inglês."