table 'analytics fct_order_items'
	lineageTag: 6d1a9542-6703-4f08-9f4f-f98c28ec0760

	column order_id
		dataType: string
		lineageTag: 975abc6e-5c42-4cfb-9d41-d52f5e72ff96
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: 850d80ec-e26c-4bba-822f-92bf872b27d2
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: b29ad859-4656-4e18-b6a2-61460b52690c
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: f0044210-e902-4393-976d-4e14a88c8405
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 09f7406d-44af-4de1-8e26-1bcd9eeeabc5
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 97a86ca4-162c-42b3-912d-a83a0c49efc2
		summarizeBy: none
		sourceColumn: purchase_date

		variation Variation
			isDefault
			relationship: 51759e7e-ffbb-4422-a658-b0d489fb3242
			defaultHierarchy: LocalDateTable_a0225297-4f56-423b-bda7-6592eee1b22a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 5fb4bd42-c7be-40fe-87d0-caed547832da
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column freight_value
		dataType: double
		lineageTag: c891ccfb-dda4-4f70-9f48-7acd61ef693d
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payment_type
		dataType: string
		lineageTag: 431dfe95-5d33-43d9-abb3-dff25ebc990c
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: d8cd2cc3-c33e-43f6-be42-2fa0fd7c8de2
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'analytics fct_order_items' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost:5435", "olist_database"),
				    analytics_fct_order_items = Fonte{[Schema="analytics",Item="fct_order_items"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(analytics_fct_order_items, each [purchase_date] > #datetime(2016, 12, 31, 0, 0, 0))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

