table 'analytics fct_orders'
	lineageTag: ed9b5a11-395f-4953-9ccf-3b53fb39db9c

	column order_id
		dataType: string
		lineageTag: d02fbe92-cd56-40c0-98d9-935e1bd33862
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 07da7f84-2afc-4bb5-92c4-f1dc7c757d61
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column total_value
		dataType: double
		lineageTag: 438135dd-b2f6-4ae9-a075-0313e278a681
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchase_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: de79043b-9a96-4517-8e23-c96130ae3f24
		summarizeBy: none
		sourceColumn: purchase_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: be6a5bb2-1c3f-4b95-9c0a-3017be93b3c8
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column approved_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 07249c53-833e-4e32-94df-deea15c99bb6
		summarizeBy: none
		sourceColumn: approved_date

		variation Variation
			isDefault
			relationship: e6451f71-389d-48b1-a478-fae61e6ef927
			defaultHierarchy: LocalDateTable_ed3aec40-b2f6-4f77-b7f2-31f92c3bd20a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dd2813d9-cccf-4fa8-a863-4f4138b36dae
		summarizeBy: none
		sourceColumn: delivered_carrier_date

		variation Variation
			isDefault
			relationship: 9ba5d1e1-9da2-40db-8483-ddf025da1713
			defaultHierarchy: LocalDateTable_fd59c80a-e8a0-4032-884b-425f8f9bd408.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column estimated_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f462409a-2d5c-40cd-9d33-887de57cc6ec
		summarizeBy: none
		sourceColumn: estimated_delivered_customer_date

		variation Variation
			isDefault
			relationship: 8a4f9d29-c9e0-4cb3-8b3c-1bddb8a161bf
			defaultHierarchy: LocalDateTable_773140c0-901d-4765-8474-91b344668a77.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column estimated_delivery_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: deaa222c-7461-4e67-9bd3-1b5a80ede2cf
		summarizeBy: none
		sourceColumn: estimated_delivery_date

		variation Variation
			isDefault
			relationship: 2c60502d-bfe3-441d-af5f-3f9a2c8b36a8
			defaultHierarchy: LocalDateTable_e1495759-8cc9-4125-a558-53768182e208.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column on_time =
			IF(
			    ISBLANK('analytics fct_orders'[delivered_carrier_date]) || ISBLANK('analytics fct_orders'[estimated_delivery_date]),
			    BLANK(),
			    IF('analytics fct_orders'[delivered_carrier_date] <= 'analytics fct_orders'[estimated_delivery_date], 1, 0)
			)
		formatString: 0
		lineageTag: b6aecc2c-adf5-4aeb-a053-97436e9871e4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'analytics fct_orders' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost:5435", "olist_database"),
				    analytics_fct_orders = Fonte{[Schema="analytics",Item="fct_orders"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(analytics_fct_orders,{{"purchase_date", type date}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [purchase_date] > #date(2016, 12, 31))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

