table Calendar
	lineageTag: dfb1f5bb-a35b-4130-986c-ef8dc1612e92

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 55d11daa-31db-4639-ae46-d8368de89b45
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 793d4979-1e3b-4f78-a5d9-ecbd93c3e08e
			defaultHierarchy: LocalDateTable_8221aa95-673c-4cad-93f3-46ca34109d62.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 0740aea3-6044-430c-90e5-c51e62d0a045
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Trimestre Num'
		dataType: int64
		formatString: 0
		lineageTag: 663f2779-b31b-4868-b11f-74c920dcdcff
		summarizeBy: sum
		sourceColumn: Trimestre Num

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: c225dadf-d5d0-4f4a-b324-01cd21d5f39b
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Ano-Trimestre
		dataType: string
		lineageTag: 6280ee4a-99c7-4d1f-8be9-cde8ae3cc786
		summarizeBy: none
		sourceColumn: Ano-Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Mês Num'
		dataType: int64
		formatString: 0
		lineageTag: 894dfe17-b0c9-4dbd-9a39-97a9fdd0eee2
		summarizeBy: sum
		sourceColumn: Mês Num

		annotation SummarizationSetBy = Automatic

	column 'Mês Nome'
		dataType: string
		lineageTag: c09b1aa9-9c78-43d3-87b9-899697f83cd1
		summarizeBy: none
		sourceColumn: Mês Nome

		annotation SummarizationSetBy = Automatic

	column 'Mês Abrev'
		dataType: string
		lineageTag: fe9b77d2-ab4d-4cdb-9e3d-f6d3a46f209f
		summarizeBy: none
		sourceColumn: Mês Abrev
		sortByColumn: 'Mês Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Ano-Mês
		dataType: string
		lineageTag: e27525f6-6598-417c-b239-c24e0e33a53e
		summarizeBy: none
		sourceColumn: Ano-Mês

		annotation SummarizationSetBy = Automatic

	column 'Ano-Mês Nome'
		dataType: string
		lineageTag: 2124e1d5-2cbb-4b02-b1d7-041932ae7de1
		summarizeBy: none
		sourceColumn: Ano-Mês Nome

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 2451c1f7-449e-437e-a524-69cd9e0005c5
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column 'Dia Semana Num'
		dataType: int64
		formatString: 0
		lineageTag: b7080ee3-b644-4cf9-ac62-91397819ceac
		summarizeBy: sum
		sourceColumn: Dia Semana Num

		annotation SummarizationSetBy = Automatic

	column 'Dia Semana'
		dataType: string
		lineageTag: 73a3923d-d719-481f-bce4-110d63249850
		summarizeBy: none
		sourceColumn: Dia Semana

		annotation SummarizationSetBy = Automatic

	column 'Dia Sem Abrev'
		dataType: string
		lineageTag: 4b38d958-d03b-4f0d-8e6a-2fe5d58fa699
		summarizeBy: none
		sourceColumn: Dia Sem Abrev

		annotation SummarizationSetBy = Automatic

	column 'É Fim de Semana'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cfd6a1c3-9db5-4bfe-9b0a-0e0f6984c7f5
		summarizeBy: none
		sourceColumn: É Fim de Semana

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: cac94d75-3307-4850-a9a5-add87e527240
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Dia do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 7f86d79d-5696-45ce-8cee-f71854897d32
		summarizeBy: sum
		sourceColumn: Dia do Ano

		annotation SummarizationSetBy = Automatic

	column 'É Mês Atual'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a9472bdd-54ae-44cf-9a35-dc8ae7628384
		summarizeBy: none
		sourceColumn: É Mês Atual

		annotation SummarizationSetBy = Automatic

	column 'É Ano Atual'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 34f3a83f-4e0b-472a-847f-07ef8589faf6
		summarizeBy: none
		sourceColumn: É Ano Atual

		annotation SummarizationSetBy = Automatic

	column 'É Hoje'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 175f6ca2-ecf0-47b2-92bf-a792898f4369
		summarizeBy: none
		sourceColumn: É Hoje

		annotation SummarizationSetBy = Automatic

	column 'Índice Data'
		dataType: int64
		formatString: 0
		lineageTag: 42577e97-d1d9-415f-bc33-fb2326bfe4b6
		summarizeBy: sum
		sourceColumn: Índice Data

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		source = ```
				let
				    // ── CONFIGURAÇÃO ─────────────────────────────────────────
				    DataInicio = #date(2017, 1, 1),
				    DataFim    = #date(2020, 12, 31),
				
				    // ── GERAÇÃO DA LISTA DE DATAS ────────────────────────────
				    TotalDias    = Duration.Days(DataFim - DataInicio) + 1,
				    ListaDatas   = List.Dates(DataInicio, TotalDias, #duration(1, 0, 0, 0)),
				    TabelaBase   = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
				    TipoData     = Table.TransformColumnTypes(TabelaBase, {{"Data", type date}}),
				
				    // ── COLUNAS DE ANO ───────────────────────────────────────
				    Ano          = Table.AddColumn(TipoData,   "Ano",              each Date.Year([Data]),                           Int64.Type),
				    
				    // ── COLUNAS DE TRIMESTRE ─────────────────────────────────
				    TrimestreNum = Table.AddColumn(Ano,        "Trimestre Num",    each Date.QuarterOfYear([Data]),                  Int64.Type),
				    Trimestre    = Table.AddColumn(TrimestreNum,"Trimestre",       each "T" & Text.From(Date.QuarterOfYear([Data])), type text),
				    AnoTrimestre = Table.AddColumn(Trimestre,  "Ano-Trimestre",    each Text.From(Date.Year([Data])) & " T" & Text.From(Date.QuarterOfYear([Data])), type text),
				
				    // ── COLUNAS DE MÊS ───────────────────────────────────────
				    MesNum       = Table.AddColumn(AnoTrimestre, "Mês Num",        each Date.Month([Data]),                          Int64.Type),
				    MesNome      = Table.AddColumn(MesNum,     "Mês Nome",         each Date.ToText([Data], "MMMM", "pt-BR"),        type text),
				    MesAbrev     = Table.AddColumn(MesNome,    "Mês Abrev",        each Date.ToText([Data], "MMM", "en-US"),         type text),
				    AnoMes       = Table.AddColumn(MesAbrev,   "Ano-Mês",          each Date.ToText([Data], "yyyy/MM"),              type text),
				    AnoMesNome   = Table.AddColumn(AnoMes,     "Ano-Mês Nome",     each Date.ToText([Data], "yyyy - MMM", "pt-BR"),  type text),
				
				    // ── COLUNAS DE SEMANA ────────────────────────────────────
				    SemanaNum    = Table.AddColumn(AnoMesNome, "Semana do Ano",    each Date.WeekOfYear([Data], Day.Monday),         Int64.Type),
				    DiaSemanaNum = Table.AddColumn(SemanaNum,  "Dia Semana Num",   each Date.DayOfWeek([Data], Day.Monday) + 1,      Int64.Type),
				    DiaSemana    = Table.AddColumn(DiaSemanaNum,"Dia Semana",      each Date.ToText([Data], "dddd", "pt-BR"),        type text),
				    DiaSemAbrev  = Table.AddColumn(DiaSemana,  "Dia Sem Abrev",    each Date.ToText([Data], "ddd", "pt-BR"),         type text),
				    EFimSemana   = Table.AddColumn(DiaSemAbrev,"É Fim de Semana",  each Date.DayOfWeek([Data], Day.Monday) >= 5,     type logical),
				
				    // ── COLUNAS DE DIA ───────────────────────────────────────
				    Dia          = Table.AddColumn(EFimSemana, "Dia",              each Date.Day([Data]),                            Int64.Type),
				    DiaDoAno     = Table.AddColumn(Dia,        "Dia do Ano",       each Date.DayOfYear([Data]),                      Int64.Type),
				
				    // ── COLUNAS DE PERÍODO ───────────────────────────────────
				    EMesAtual    = Table.AddColumn(DiaDoAno,   "É Mês Atual",      each Date.Year([Data]) = Date.Year(DateTime.LocalNow()) and Date.Month([Data]) = Date.Month(DateTime.LocalNow()), type logical),
				    EAnoAtual    = Table.AddColumn(EMesAtual,  "É Ano Atual",      each Date.Year([Data]) = Date.Year(DateTime.LocalNow()), type logical),
				    EHoje        = Table.AddColumn(EAnoAtual,  "É Hoje",           each [Data] = DateTime.Date(DateTime.LocalNow()), type logical),
				
				    // ── ÍNDICE PARA ORDENAÇÃO ────────────────────────────────
				    Indice       = Table.AddColumn(EHoje,      "Índice Data",      each Date.Year([Data]) * 10000 + Date.Month([Data]) * 100 + Date.Day([Data]), Int64.Type),
				
				    // ── RESULTADO FINAL ──────────────────────────────────────
				    Resultado    = Table.Sort(Indice, {{"Data", Order.Ascending}})
				
				in
				    Resultado
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

