table Medidas
	lineageTag: 6fc7ebf3-bc86-431a-9cba-729749162a78

	measure embranco = BLANK()
		formatString: 0
		lineageTag: 4d4f61a2-8ad4-4410-9199-19351e088cbb

	measure 'Total Revenue' = SUM('analytics fct_orders'[total_value])
		lineageTag: ddf515a8-6f5a-4a13-a9d5-bc1e5dd8c595

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = COUNT('analytics fct_orders'[order_id])
		formatString: #,0
		lineageTag: 61d13153-e593-42f9-ac82-501df73f6b17

	measure AOV = DIVIDE([Total Revenue], [Total Orders], 0)
		lineageTag: 254a082d-c9b6-4871-b254-4e3e2b2b4cd9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Satisfaction' = AVERAGE('analytics fct_orders'[review_score])
		lineageTag: 14dad811-92a4-4c85-98c9-8f4a32e01d04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delivery Delay Days' =
			
			AVERAGEX(
			    'analytics fct_orders',
			    DATEDIFF('analytics fct_orders'[estimated_delivery_date], 'analytics fct_orders'[delivered_carrier_date], DAY)
			)
		lineageTag: 56ae4707-2e73-4792-a9f5-a212c97e806f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Review Score' = AVERAGE('analytics fct_orders'[review_score])
		lineageTag: f0450fa9-1681-496c-8df4-acf9b7692757

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Time Delivery %' = DIVIDE(SUM('analytics fct_orders'[on_time]), COUNTROWS(FILTER('analytics fct_orders', NOT(ISBLANK('analytics fct_orders'[on_time])))))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 89610b6a-3f89-41a3-95b2-a1d542552000

	measure olist_title = "Olist Dashboard"
		lineageTag: 43430fa3-0022-4781-b7bf-065d47b930be

	column Medidas
		dataType: string
		lineageTag: 0c0a4b99-4315-422b-b1af-3b30cb0f794a
		summarizeBy: none
		sourceColumn: Medidas

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = ""
				in
				    Fonte

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Text

