# Nomeie seu projeto! Nomes de projeto devem conter apenas caracteres minúsculos
# e underscores. Um bom nome de pacote deve refletir o nome da sua organização
# ou o uso pretendido dos modelos
name: 'dbt_olist'
version: '1.0.0'

# Esta configuração define qual "profile" o dbt usa para este projeto.
profile: 'dbt_olist'

# Estas configurações especificam onde o dbt deve procurar por diferentes tipos de arquivos.
# A configuração `model-paths`, por exemplo, indica que os modelos deste projeto podem ser
# encontrados no diretório "models/". Provavelmente você não precisará alterar isso!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # diretórios a serem removidos pelo comando `dbt clean`
  - "target"
  - "dbt_packages"


# Configurando modelos
# Documentação completa: https://docs.getdbt.com/docs/configuring-models

# Neste exemplo de configuração, dizemos ao dbt para construir todos os modelos
# do diretório example/ como views. Estas configurações podem ser sobrescritas
# nos arquivos individuais de modelo usando a macro `{{ config(...) }}`.
models:
  dbt_olist:
    marts:
      +materialized: table